### ISSUE TITLE
destination path 'source' already exists and is not an empty directory

### ISSUE THREAD

**Issue by zhongpan** [wei/git-sync#10]
When synchronizing from master to master, the following error is reported:
fatal: destination path 'source' already exists and is not an empty directory.
fatal: 'source' does not appear to be a git repository
fatal: Could not read from remote repository.

This error starts from v1.1.3

**Comment by wei** [comment]
Thank you. On it.

**Comment by wei** [comment]
What's your workflow like? Are you running more than one `wei/git-sync` action in one workflow file?

**Comment by wei** [comment]
Please try v1.1.4

**Comment by zhongpan** [comment]
After switching to v2, the problem has been solved. Thanks.
