### ISSUE TITLE
[Bug] failing validation check on GitHub repo slug

### ISSUE THREAD

**Issue by shakti-garg** [wei/git-sync#20]
If source or destination repo is "https://github.com/shakti-garg/datahub", the whole script should fail as it is neither a repo slug nor full clone url.

Reason:
In git-sync.sh, the following condition is failing
```
if ! echo $SOURCE_REPO | grep '.git'
```
as grep is using a special regex character '.'

**Comment by wei** [comment]
Thanks for the PR, I'll test it when I have some time. Btw, `git clone https://github.com/shakti-garg/datahub` works fine as GitHub treats this as a good full clone url.
