### ISSUE TITLE
Two-way Sync

### ISSUE THREAD

**Issue by arnold-c** [wei/git-sync#33]
Hi,

I was just wondering if there is a way to get the action to sync in both directions? I have a private and public version of a repository that I'm hoping to keep linked, and currently have it syncing between `source: private/public` and `destination: public/main` branches, but if there is two-way sync, I suspect this is creating an issue when the actions `main.yml` file is being copied from the private as the source and destination branches should now be reversed.

Thanks,

**Comment by wei** [comment]
I suggest using a different repo to run the workflow. Just test and make sure the changes in the repos are not overwritten when you do it both ways.

**Comment by arnold-c** [comment]
Sorry, to clarify, are you suggesting that I open a 3rd repository that runs the workflow? If that's the case, I think it might just be easier to make sure the source and destination branches are the same name

**Comment by wei** [comment]
You can use secrets to supply the variables. So workflow files will be the same but branch can come from repo secret.

**Comment by arnold-c** [comment]
Thanks @wei - using secrets worked perfectly!
