### ISSUE TITLE
[Question] Is there a way to sync pull requests? 

### ISSUE THREAD

**Issue by PenzinAlexander** [wei/git-sync#34]
Hey. Thanks for this action. 
I want to sync Github's Pull Request into Gitlab's Merge Requests. 
Is there a way to make it? 

Thank you!

**Comment by wei** [comment]
This action does not support syncing pull requests to GitLab merge requests at this time. You can write a custom GitHub action on pull-request open and make an API call to GitLab to create merge requests.
