### ISSUE TITLE
Can it be used to sync github and gitlab?

### ISSUE THREAD

**Issue by chirag127** [wei/git-sync#45]
how to sync GitHub and GitLab? like I want to take a backup of GitHub to GitLab.

**Comment by wei** [comment]
Yes!

**Comment by chirag127** [comment]
how?
so, i will need to do it manually for each repository?

**Comment by chirag127** [comment]
?

**Comment by wei** [comment]
Please see README for an example using GitLab. You will need to add multiple steps one for each repo.
