### ISSUE TITLE
[Question] Why does it wipe out all my commits?

### ISSUE THREAD

**Issue by yodaluca23** [wei/git-sync#46]
From my understanding, this worked, similarly to the GitHub Bot "[Pull](https://github.com/wei/pull)", except, that it did not have to be in the same fork network, and could be a private repo, but I set it up successfully, and ran it, but (Now luckily it was not my main fork, but a clone of it.) it cleared all of my commits, and made it identical to the source repo, I thought, like the Pull bot, it would make a PR that merges the new (since cloning) commits, of the source repo, if there were any...

**Comment by wei** [comment]
This action actually does wipe all commits so source and destination match exactly. I misunderstood your initial requirement. What you're looking for is actually https://github.com/repo-sync/repo-sync which is what GitHub Docs team use to keep forks (not in the same fork network) in sync.
