### ISSUE TITLE
feature: exclude files/directories from being pushed

### ISSUE THREAD

**Issue by Xat59** [wei/git-sync#47]
Hi,

I suggest to add a new feature that allows us to synchronize the repository by excluding files and/or directories.

Reasons for this feature could be multiple. In my case I don't want to sync the `.github` folder cause it makes no sense to have it on my custom github instance that does allow execution of workflow based on public workflow.

That could looks like the following :

```
exclude_dir:
  - .github
exclude_file:
  - file_to_not_be_synced
```

Regards.

**Comment by wei** [comment]
Hi there thanks for the suggestion. However, git doesn't work like this because each commit hash is unique, changing files or excluding a directory will require a new commit and a new hash which is currently not in the plans for this action.
