### ISSUE TITLE
Add automatic testing

### ISSUE THREAD

**Issue by rasodu** [wei/git-sync#6]
This will allow features to be merged faster
1. Create repository 'wei/git-sync-downstream'
2. Create a new Github action in 'wei/git-sync' : push-to-downstream
    - Automatically push branch(only the branch that gets update) to 'wei/git-sync-downstream'

Not totally sure that this will work though.

**Comment by wei** [comment]
This would be nice if we had it for #22, PR welcome. Closing for now.
